openai:
  model: "gpt-4o-2024-08-06" # gpt-4o-2024-08-06 | gpt-4o-turbo | gpt-4o
  base_url: "https://api.gptsapi.net/v1"
  api_key: "sk-BwRe50036e3a52620eed60c6f72d1a566d783d4bce6oYak2"

tool_openai:
  model: "gpt-4o-2024-08-06" # gpt-4o-2024-08-06 | gpt-4o-turbo | gpt-4o
  base_url: "https://api.gptsapi.net/v1"
  api_key: "sk-BwRe50036e3a52620eed60c6f72d1a566d783d4bce6oYak2"


application:
  notepad:
    path: "C:/Windows/System32/notepad.exe"
    alias: ["Windows 记事本"]
  google:
    path: "C:/Program Files/Google/Chrome/Application/chrome.exe"
    alias: ["Google Chrome 浏览器", "谷歌浏览器", "Chrome 浏览器", "谷歌", "Google浏览器"]
  edge:
    path: "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
    alias: ["Microsoft Edge 浏览器"]
  excel:
    path: "C:/Program Files/Microsoft Office/root/Office16/EXCEL.EXE"
    alias: ["Microsoft Excel 表格编辑器"]
  word:
    path: "C:/Program Files/Microsoft Office/root/Office16/WINWORD.EXE"
    alias: ["Microsoft Word 文档编辑器"]
  QQMusic:
    path: "D:/software/daily/QQMusic/QQMusic.exe"
    alias: ["QQ音乐"]
  wangyiyun:
    path: "D:/software/daily/NeteaseCloudMusic/CloudMusic/cloudmusic.exe"
    alias: ["网易云音乐", "网易云", "云音乐"]

ui_control:
  backend: "uia"
  control_type_list: ["Button", "Edit", "TabItem", "Document", "ListItem", "MenuItem", "ScrollBar", "TreeItem", "Hyperlink", "ComboBox", "RadioButton", "DataItem", "Spinner"]
  class_name_list: []
  image_basic_path: "images/desktop/"
  image_suffix: ".png"
  is_visible: true

os: "Windows"
screen_resolution:
  width: 1920
  height: 1080
  taskbar_height: 40

db:
  host: "8.134.39.162"
  port: 3306
  user: "root"
  password: "123456"
  database: "agent"
