TEAM_ROUND_ROBIN = 1
TEAM_SELECT_GROUP = 2
TEAM_SWAM = 3

ELEMENT_OPERATION_SINGLE_CLICK = 1
ELEMENT_OPERATION_DOUBLE_CLICK = 2
ELEMENT_OPERATION_INPUT_TEXT = 3
ELEMENT_OPERATION_INPUT_AND_ENTER = 4

AGENT_ASSISTANT = 1
AGENT_OPENAI_ASSISTANT = 2
